const actionTypes = {
	/* Video */
	PAUSE_VIDEO: 'PAUSE_VIDEO',
	RESUME_VIDEO: 'RESUME_VIDEO',

	LOACTE_START: 'LOACTE_START',
	LOACTE_SUCCESS: 'LOACTE_SUCCESS',
	LOACTE_FAILED: 'LOACTE_FAILED',

	RESET_START: 'RESET_START',
	RESET_SUCCESS: 'RESET_SUCCESS',
	RESET_FAILED: 'RESET_FAILED',

	TAKE_OFF_START: 'TAKE_OFF_START',
	TAKE_OFF_SUCCESS: 'TAKE_OFF_SUCCESS',
	TAKE_OFF_FAILED: 'TAKE_OFF_FAILED',

	SET_EXPOSURE_START: 'SET_EXPOSURE_START',
	SET_EXPOSURE_SUCCESS: 'SET_EXPOSURE_SUCCESS',
	SET_EXPOSURE_FAILED: 'SET_EXPOSURE_FAILED',

	TOGGLE_ARM_STATE: 'TOGGLE_ARM_STATE',
	
	START_INDOOR_EXPLORATION: 'START_INDOOR_EXPLORATION',
	SET_INDOOR_EXPLORATION_FLAG: 'SET_INDOOR_EXPLORATION_FLAG',
	REMOVE_INDOOR_EXPLORATION_FLAG: 'REMOVE_INDOOR_EXPLORATION_FLAG',
	SET_MISSION_STATE: 'SET_MISSION_STATE',

	GO_TO_LOCATION_START: 'GO_TO_LOCATION_START',
	GO_TO_LOCATION_SUCCESS: 'GO_TO_LOCATION_SUCCESS',
	GO_TO_LOCATION_FAILED: 'GO_TO_LOCATION_FAILED',

	POINT_ON_VIDEO_IMAGE_START: 'POINT_ON_VIDEO_IMAGE_START',
	POINT_ON_VIDEO_IMAGE_SUCCESS: 'POINT_ON_VIDEO_IMAGE_SUCCESS',
	POINT_ON_VIDEO_IMAGE_FAILED: 'POINT_ON_VIDEO_IMAGE_FAILED',

	ROSS_WEBSOCKET_CONNECTION_SUCCESS: 'ROSS_WEBSOCKET_CONNECTION_SUCCESS',
	ROSS_WEBSOCKET_CONNECTION_FAILED: 'ROSS_WEBSOCKET_CONNECTION_FAILED',
	ROSS_WEBSOCKET_CONNECTION_CLOSED: 'ROSS_WEBSOCKET_CONNECTION_CLOSED',
	ROSS_WEBSOCKET_CONNECTION_START: 'ROSS_WEBSOCKET_CONNECTION_START',

	/* UI */
	SHOW_GLOBAL_MESSAGE: 'SHOW_GLOBAL_MESSAGE',
	REMOVE_GLOBAL_MESSAGE: 'REMOVE_GLOBAL_MESSAGE',
	SHOW_CONTEXT_MENU: 'SHOW_CONTEXT_MENU',
	CLOSE_CONTEXT_MENU: 'CLOSE_CONTEXT_MENU',
	SHOW_POPUP: 'SHOW_POPUP',
	HIDE_POPUP: 'HIDE_POPUP',
	IMAGE_SENT_TO_DRONE: 'IMAGE_SENT_TO_DRONE',
	TOGGLE_MISSION_PLANNER_SCREEN: 'TOGGLE_MISSION_PLANNER_SCREEN',
	SELECT_DRONE: 'SELECT_DRONE',
	TOGGLE_MAP_AND_OUTPUT_TABS: 'TOGGLE_MAP_AND_OUTPUT_TABS',
	SET_BATTERY_LEVEL: 'SET_BATTERY_LEVEL',

	/* Map */
	SET_MAPCORE_SDK_LOADED_FLAG: 'SET_MAPCORE_SDK_LOADED_FLAG',
	SET_MAP_TO_SHOW: 'SET_MAP_TO_SHOW' ,
	GET_DRONE_POSITION_OFFSET: 'GET_DRONE_POSITION_OFFSET',
	GET_ENEMY_POSITION:'GET_ENEMY_POSITION',
	SAVE_ORIGIN_COORDINATE: 'SAVE_ORIGIN_COORDINATE',
	DELETE_DRONE_POSITION: 'DELETE_DRONE_POSITION',
	TOGGLE_POINT_SELECTION_MODE : 'TOGGLE_POINT_SELECTION_MODE',
	SELECT_POINT_FROM_MAP :'SELECT_POINT_FROM_MAP',
	

	/* Output */
	UPDATE_SKELETON_RANGE: 'UPDATE_SKELETON_RANGE',
	SET_WEAPON_DETECTION: 'SET_WEAPON_DETECTION',
	
	/*Planner */	
	ADD_NEW_MISSION_PLAN_STAGE: 'ADD_NEW_MISSION_PLAN_STAGE',
	DELETE_MISSION_PLAN_STAGE: 'DELETE_MISSION_PLAN_STAGE',
	EDIT_MISSION_PLAN_STAGE: 'EDIT_MISSION_PLAN_STAGE',
	MOVE_UP_MISSION_PLAN_STAGE: 'MOVE_UP_MISSION_PLAN_STAGE',
	MOVE_DOWN_MISSION_PLAN_STAGE: 'MOVE_DOWN_MISSION_PLAN_STAGE',
	SAVE_MISSION_PLAN: 'SAVE_MISSION_PLAN',
	REMOVE_DRAFT_MISSION_PLAN: 'REMOVE_DRAFT_MISSION_PLAN',
	REMOVE_SAVED_MISSION_PLAN: 'REMOVE_SAVED_MISSION_PLAN',
	TOGGLE_MISSION_PLAN_VIEWER_STATE: 'TOGGLE_MISSION_PLAN_VIEWER_STATE',
	LOAD_DEFAULT_PLAN: 'LOAD_DEFAULT_PLAN',
};
export default actionTypes;
