const actionTypes = {
	PAUSE_VIDEO: 'PAUSE_VIDEO',
	RESUME_VIDEO: 'RESUME_VIDEO',

	LOACTE_START: 'LOACTE_START',
	LOACTE_SUCCESS: 'LOACTE_SUCCESS',
	LOACTE_FAILED: 'LOACTE_FAILED',

	RESET_START: 'RESET_START',
	RESET_SUCCESS: 'RESET_SUCCESS',
	RESET_FAILED: 'RESET_FAILED',

	TAKE_OFF_START: 'TAKE_OFF_START',
	TAKE_OFF_SUCCESS: 'TAKE_OFF_SUCCESS',
	TAKE_OFF_FAILED: 'TAKE_OFF_FAILED',

	POINT_ON_VIDEO_IMAGE_START: 'POINT_ON_VIDEO_IMAGE_START',
	POINT_ON_VIDEO_IMAGE_SUCCESS: 'POINT_ON_VIDEO_IMAGE_SUCCESS',
	POINT_ON_VIDEO_IMAGE_FAILED: 'POINT_ON_VIDEO_IMAGE_FAILED',

	ROSS_WEBSOCKET_CONNECTION_SUCCESS: 'ROSS_WEBSOCKET_CONNECTION_SUCCESS',
	ROSS_WEBSOCKET_CONNECTION_FAILED: 'ROSS_WEBSOCKET_CONNECTION_FAILED',
	ROSS_WEBSOCKET_CONNECTION_CLOSED: 'ROSS_WEBSOCKET_CONNECTION_CLOSED',
	ROSS_WEBSOCKET_CONNECTION_START: 'ROSS_WEBSOCKET_CONNECTION_START',

	SHOW_GLOBAL_MESSAGE: 'SHOW_GLOBAL_MESSAGE',

	
};
export default actionTypes;
